openapi: 3.0.0
info:
  title: Proxy/Singleton Pattern API
  version: 1.0.0
servers:
  - url: http://localhost:1337
paths:
  /api/product:
    get:
      tags:
        - product
      summary: Get All Products
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - product
      summary: Create New Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: iPhone 14
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}